"""add watchlist and dates

Revision ID: 7e38c9ecf58a
Revises: 2f4a6c8e0b12
Create Date: 2026-01-09 14:29:08.022508

"""
from alembic import op
import sqlalchemy as sa



revision = '7e38c9ecf58a'
down_revision = '2f4a6c8e0b12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('media_item_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'media_item_id', name='uq_watchlist_items_user_media')
    )
    op.create_index(op.f('ix_watchlist_items_media_item_id'), 'watchlist_items', ['media_item_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_status'), 'watchlist_items', ['status'], unique=False)
    op.create_index(op.f('ix_watchlist_items_user_id'), 'watchlist_items', ['user_id'], unique=False)
    op.create_index('ix_watchlist_items_user_status', 'watchlist_items', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_blacklist_items_imdb_id'), 'blacklist_items', ['imdb_id'], unique=False)
    op.create_index(op.f('ix_blacklist_items_tmdb_id'), 'blacklist_items', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_blacklist_items_tvdb_id'), 'blacklist_items', ['tvdb_id'], unique=False)
    op.create_index(op.f('ix_blacklist_items_tvmaze_id'), 'blacklist_items', ['tvmaze_id'], unique=False)
    op.create_index(op.f('ix_blacklist_items_user_id'), 'blacklist_items', ['user_id'], unique=False)
    op.add_column('episode_items', sa.Column('air_date', sa.Date(), nullable=True))
    op.add_column('media_items', sa.Column('release_date', sa.Date(), nullable=True))
    op.add_column('media_items', sa.Column('first_air_date', sa.Date(), nullable=True))
    op.add_column('media_items', sa.Column('last_air_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_items', 'last_air_date')
    op.drop_column('media_items', 'first_air_date')
    op.drop_column('media_items', 'release_date')
    op.drop_column('episode_items', 'air_date')
    op.drop_index(op.f('ix_blacklist_items_user_id'), table_name='blacklist_items')
    op.drop_index(op.f('ix_blacklist_items_tvmaze_id'), table_name='blacklist_items')
    op.drop_index(op.f('ix_blacklist_items_tvdb_id'), table_name='blacklist_items')
    op.drop_index(op.f('ix_blacklist_items_tmdb_id'), table_name='blacklist_items')
    op.drop_index(op.f('ix_blacklist_items_imdb_id'), table_name='blacklist_items')
    op.drop_index('ix_watchlist_items_user_status', table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_user_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_status'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_media_item_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    # ### end Alembic commands ###
