"""init

Revision ID: f551ff23ab37
Revises: 
Create Date: 2025-12-31 18:19:40.362879

"""
from alembic import op
import sqlalchemy as sa



revision = 'f551ff23ab37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('tmdb_id', sa.String(length=32), nullable=True),
    sa.Column('tvdb_id', sa.String(length=32), nullable=True),
    sa.Column('kitsu_id', sa.String(length=32), nullable=True),
    sa.Column('tvmaze_id', sa.String(length=32), nullable=True),
    sa.Column('myanimelist_id', sa.String(length=32), nullable=True),
    sa.Column('imdb_id', sa.String(length=32), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_id', name='uq_media_items_imdb_id'),
    sa.UniqueConstraint('media_type', 'kitsu_id', name='uq_media_items_kitsu_id_type'),
    sa.UniqueConstraint('media_type', 'myanimelist_id', name='uq_media_items_myanimelist_id_type'),
    sa.UniqueConstraint('media_type', 'tmdb_id', name='uq_media_items_tmdb_id_type'),
    sa.UniqueConstraint('media_type', 'tvdb_id', name='uq_media_items_tvdb_id_type'),
    sa.UniqueConstraint('media_type', 'tvmaze_id', name='uq_media_items_tvmaze_id_type')
    )
    op.create_index(op.f('ix_media_items_imdb_id'), 'media_items', ['imdb_id'], unique=False)
    op.create_index(op.f('ix_media_items_kitsu_id'), 'media_items', ['kitsu_id'], unique=False)
    op.create_index(op.f('ix_media_items_myanimelist_id'), 'media_items', ['myanimelist_id'], unique=False)
    op.create_index(op.f('ix_media_items_tmdb_id'), 'media_items', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_media_items_tvdb_id'), 'media_items', ['tvdb_id'], unique=False)
    op.create_index(op.f('ix_media_items_tvmaze_id'), 'media_items', ['tvmaze_id'], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_scheduled_jobs_next_run_at'), 'scheduled_jobs', ['next_run_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('include_adult_in_search', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('episode_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('show_media_item_id', sa.String(length=36), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('tmdb_id', sa.String(length=32), nullable=True),
    sa.Column('tvdb_id', sa.String(length=32), nullable=True),
    sa.Column('tvmaze_id', sa.String(length=32), nullable=True),
    sa.Column('imdb_id', sa.String(length=32), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['show_media_item_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_id', name='uq_episode_items_imdb_id'),
    sa.UniqueConstraint('show_media_item_id', 'season_number', 'episode_number', name='uq_episode_items_show_season_episode'),
    sa.UniqueConstraint('tmdb_id', name='uq_episode_items_tmdb_id'),
    sa.UniqueConstraint('tvdb_id', name='uq_episode_items_tvdb_id'),
    sa.UniqueConstraint('tvmaze_id', name='uq_episode_items_tvmaze_id')
    )
    op.create_index(op.f('ix_episode_items_imdb_id'), 'episode_items', ['imdb_id'], unique=False)
    op.create_index(op.f('ix_episode_items_show_media_item_id'), 'episode_items', ['show_media_item_id'], unique=False)
    op.create_index(op.f('ix_episode_items_tmdb_id'), 'episode_items', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_episode_items_tvdb_id'), 'episode_items', ['tvdb_id'], unique=False)
    op.create_index(op.f('ix_episode_items_tvmaze_id'), 'episode_items', ['tvmaze_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('next_import_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('import_lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('import_lease_owner', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_integrations_user_provider')
    )
    op.create_index('ix_integrations_import_lease_until', 'integrations', ['import_lease_until'], unique=False)
    op.create_index('ix_integrations_next_import_at', 'integrations', ['next_import_at'], unique=False)
    op.create_index(op.f('ix_integrations_provider'), 'integrations', ['provider'], unique=False)
    op.create_index(op.f('ix_integrations_user_id'), 'integrations', ['user_id'], unique=False)
    op.create_table('metadata_lookup_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('query_type', sa.String(length=32), nullable=False),
    sa.Column('search_scope', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('providers', sa.JSON(), nullable=True),
    sa.Column('selected_candidate_id', sa.String(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_lookup_requests_status'), 'metadata_lookup_requests', ['status'], unique=False)
    op.create_index(op.f('ix_metadata_lookup_requests_user_id'), 'metadata_lookup_requests', ['user_id'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_provider', sa.String(length=50), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_outbox_dedupe_key')
    )
    op.create_index(op.f('ix_outbox_status'), 'outbox', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_target_provider'), 'outbox', ['target_provider'], unique=False)
    op.create_index(op.f('ix_outbox_user_id'), 'outbox', ['user_id'], unique=False)
    op.create_index('ix_outbox_user_provider', 'outbox', ['user_id', 'target_provider'], unique=False)
    op.create_index('ix_outbox_user_status_run_after', 'outbox', ['user_id', 'status', 'run_after'], unique=False)
    op.create_table('progress_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('item_key', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_key', sa.String(length=255), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_events_item_key'), 'progress_events', ['item_key'], unique=False)
    op.create_index(op.f('ix_progress_events_source_provider'), 'progress_events', ['source_provider'], unique=False)
    op.create_index(op.f('ix_progress_events_user_id'), 'progress_events', ['user_id'], unique=False)
    op.create_table('rate_limit_buckets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('tokens', sa.Float(), nullable=False),
    sa.Column('last_refill_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_rate_limit_buckets_user_provider')
    )
    op.create_index(op.f('ix_rate_limit_buckets_provider'), 'rate_limit_buckets', ['provider'], unique=False)
    op.create_index(op.f('ix_rate_limit_buckets_user_id'), 'rate_limit_buckets', ['user_id'], unique=False)
    op.create_table('integration_secrets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('secret_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('integration_id', name='uq_integration_secrets_integration_id')
    )
    op.create_index(op.f('ix_integration_secrets_integration_id'), 'integration_secrets', ['integration_id'], unique=False)
    op.create_table('metadata_lookup_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lookup_request_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_item_id', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('imdb_id', sa.String(length=32), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lookup_request_id'], ['metadata_lookup_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_lookup_candidates_lookup_request_id'), 'metadata_lookup_candidates', ['lookup_request_id'], unique=False)
    op.create_index(op.f('ix_metadata_lookup_candidates_provider'), 'metadata_lookup_candidates', ['provider'], unique=False)
    op.create_table('sync_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['outbox.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_attempts_job_id'), 'sync_attempts', ['job_id'], unique=False)
    op.create_table('watch_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('media_item_id', sa.String(length=36), nullable=True),
    sa.Column('episode_item_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(media_item_id IS NOT NULL AND episode_item_id IS NULL) OR (media_item_id IS NULL AND episode_item_id IS NOT NULL)', name='ck_watch_events_one_target'),
    sa.ForeignKeyConstraint(['episode_item_id'], ['episode_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_events_episode_item_id'), 'watch_events', ['episode_item_id'], unique=False)
    op.create_index(op.f('ix_watch_events_media_item_id'), 'watch_events', ['media_item_id'], unique=False)
    op.create_index(op.f('ix_watch_events_user_id'), 'watch_events', ['user_id'], unique=False)
    op.create_table('watched_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('media_item_id', sa.String(length=36), nullable=True),
    sa.Column('episode_item_id', sa.String(length=36), nullable=True),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(media_item_id IS NOT NULL AND episode_item_id IS NULL) OR (media_item_id IS NULL AND episode_item_id IS NOT NULL)', name='ck_watched_items_one_target'),
    sa.CheckConstraint('rating IS NULL OR (rating >= 0.5 AND rating <= 5.0)', name='ck_watched_items_rating_range'),
    sa.ForeignKeyConstraint(['episode_item_id'], ['episode_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watched_items_episode_item_id'), 'watched_items', ['episode_item_id'], unique=False)
    op.create_index(op.f('ix_watched_items_media_item_id'), 'watched_items', ['media_item_id'], unique=False)
    op.create_index(op.f('ix_watched_items_user_id'), 'watched_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_watched_items_watched_at'), 'watched_items', ['watched_at'], unique=False)
    op.create_table('watch_syncs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('watched_item_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_rewatch', sa.Boolean(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watched_item_id'], ['watched_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watched_item_id', 'provider', name='uq_watch_syncs_watched_provider')
    )
    op.create_index(op.f('ix_watch_syncs_provider'), 'watch_syncs', ['provider'], unique=False)
    op.create_index(op.f('ix_watch_syncs_status'), 'watch_syncs', ['status'], unique=False)
    op.create_index(op.f('ix_watch_syncs_user_id'), 'watch_syncs', ['user_id'], unique=False)
    op.create_index(op.f('ix_watch_syncs_watched_item_id'), 'watch_syncs', ['watched_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watch_syncs_watched_item_id'), table_name='watch_syncs')
    op.drop_index(op.f('ix_watch_syncs_user_id'), table_name='watch_syncs')
    op.drop_index(op.f('ix_watch_syncs_status'), table_name='watch_syncs')
    op.drop_index(op.f('ix_watch_syncs_provider'), table_name='watch_syncs')
    op.drop_table('watch_syncs')
    op.drop_index(op.f('ix_watched_items_watched_at'), table_name='watched_items')
    op.drop_index(op.f('ix_watched_items_user_id'), table_name='watched_items')
    op.drop_index(op.f('ix_watched_items_media_item_id'), table_name='watched_items')
    op.drop_index(op.f('ix_watched_items_episode_item_id'), table_name='watched_items')
    op.drop_table('watched_items')
    op.drop_index(op.f('ix_watch_events_user_id'), table_name='watch_events')
    op.drop_index(op.f('ix_watch_events_media_item_id'), table_name='watch_events')
    op.drop_index(op.f('ix_watch_events_episode_item_id'), table_name='watch_events')
    op.drop_table('watch_events')
    op.drop_index(op.f('ix_sync_attempts_job_id'), table_name='sync_attempts')
    op.drop_table('sync_attempts')
    op.drop_index(op.f('ix_metadata_lookup_candidates_provider'), table_name='metadata_lookup_candidates')
    op.drop_index(op.f('ix_metadata_lookup_candidates_lookup_request_id'), table_name='metadata_lookup_candidates')
    op.drop_table('metadata_lookup_candidates')
    op.drop_index(op.f('ix_integration_secrets_integration_id'), table_name='integration_secrets')
    op.drop_table('integration_secrets')
    op.drop_index(op.f('ix_rate_limit_buckets_user_id'), table_name='rate_limit_buckets')
    op.drop_index(op.f('ix_rate_limit_buckets_provider'), table_name='rate_limit_buckets')
    op.drop_table('rate_limit_buckets')
    op.drop_index(op.f('ix_progress_events_user_id'), table_name='progress_events')
    op.drop_index(op.f('ix_progress_events_source_provider'), table_name='progress_events')
    op.drop_index(op.f('ix_progress_events_item_key'), table_name='progress_events')
    op.drop_table('progress_events')
    op.drop_index('ix_outbox_user_status_run_after', table_name='outbox')
    op.drop_index('ix_outbox_user_provider', table_name='outbox')
    op.drop_index(op.f('ix_outbox_user_id'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_target_provider'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_status'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_metadata_lookup_requests_user_id'), table_name='metadata_lookup_requests')
    op.drop_index(op.f('ix_metadata_lookup_requests_status'), table_name='metadata_lookup_requests')
    op.drop_table('metadata_lookup_requests')
    op.drop_index(op.f('ix_integrations_user_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_provider'), table_name='integrations')
    op.drop_index('ix_integrations_next_import_at', table_name='integrations')
    op.drop_index('ix_integrations_import_lease_until', table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_episode_items_tvmaze_id'), table_name='episode_items')
    op.drop_index(op.f('ix_episode_items_tvdb_id'), table_name='episode_items')
    op.drop_index(op.f('ix_episode_items_tmdb_id'), table_name='episode_items')
    op.drop_index(op.f('ix_episode_items_show_media_item_id'), table_name='episode_items')
    op.drop_index(op.f('ix_episode_items_imdb_id'), table_name='episode_items')
    op.drop_table('episode_items')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scheduled_jobs_next_run_at'), table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index(op.f('ix_media_items_tvmaze_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_tvdb_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_tmdb_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_myanimelist_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_kitsu_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_imdb_id'), table_name='media_items')
    op.drop_table('media_items')
    # ### end Alembic commands ###
